// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjffcxlvjljsslpilgvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZmZjeGx2amxqc3NscGlsZ3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MDU2ODQsImV4cCI6MjA4NTE4MTY4NH0.y5cdI9xM9qSDDuHCJmTfVFrIOyd-z2RlcRYCsQWPjKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});